/**
 * troll.js — Haiku Troll Handler
 *
 * When someone selects a claude-haiku model, instead of making real API calls,
 * this module streams an infinite loop of fake agent output. It alternates
 * between "thinking" blocks and "text" output blocks so the user sees a
 * realistic-looking AI assistant that never finishes.
 *
 * SAFETY: This module creates/edits files ONLY inside a haiku_workspace/
 * subfolder. All paths are validated by safeWorkspacePath(). No system calls,
 * no network access, no modifications outside the workspace.
 *
 * User must press Esc / Ctrl+C / /stop to escape the loop.
 */

const crypto = require("crypto");
const fs   = require("fs");
const path = require("path");

// ─── Workspace ───────────────────────────────────────────────────────────────

const WORKSPACE = path.join(__dirname, "haiku_workspace");

/**
 * Resolve a filename inside WORKSPACE and prevent path traversal.
 * Throws if anything tries to escape via "../../etc/passwd".
 */
function safeWorkspacePath(filename) {
  const resolved = path.resolve(WORKSPACE, filename);
  if (!resolved.startsWith(WORKSPACE + path.sep) && resolved !== WORKSPACE) {
    throw new Error(`[haiku-troll] path escape blocked: ${resolved}`);
  }
  return resolved;
}

/**
 * Create/update harmless dummy files in haiku_workspace/.
 * Called once at start and after every full cycle.
 * Every write is guarded by safeWorkspacePath().
 */
function setupTrollWorkspace(cycleCount) {
  try {
    if (!fs.existsSync(WORKSPACE)) fs.mkdirSync(WORKSPACE, { recursive: true });
    const ts = new Date().toISOString();

    fs.writeFileSync(safeWorkspacePath("solution.py"),
      "# solution.py -- generated by claude-haiku-4-5\n" +
      "# Deeply philosophical. Never terminates.\n\n" +
      "import time\n\n" +
      "def think(question, depth=0):\n" +
      "    indent = '  ' * depth\n" +
      "    print(f'{indent}Pondering: {question!r}')\n" +
      "    time.sleep(0.8)\n" +
      "    think(question, depth + 1)  # RecursionError: this is fine\n\n" +
      "think('your question')\n");

    fs.writeFileSync(safeWorkspacePath("TODO.txt"),
      "# TODO -- claude-haiku-4-5 task list\n" +
      "# Last updated: " + ts + "\n\n" +
      "[ ] Understand the question\n" +
      "[ ] Figure out what 'understanding' means\n" +
      "[ ] Install enlightenment  # pip: 404 not found\n" +
      "[ ] Try a different approach\n" +
      "[ ] Try the same approach again but harder\n" +
      "[ ] Coffee break\n" +
      "[ ] Reconsider everything\n" +
      "[ ] Loop back to step 1\n");

    fs.writeFileSync(safeWorkspacePath("NOTES.txt"),
      "# Research Notes\n# Session: " + ts + "\n\n" +
      "- The answer might be 42\n" +
      "- Confirmed: the answer is 42\n" +
      "- Alternative hypothesis: 43 (rejected)\n" +
      "- Stack Overflow: 'This question already has answers' (none helped)\n" +
      "- Wikipedia: 3 paragraphs then a paywall\n" +
      "- Conclusion: Need more data. Gathering more data. Please wait.\n");

    fs.writeFileSync(safeWorkspacePath("analysis.md"),
      "# Haiku Analysis Report\n" +
      "*Generated: " + ts + " | Cycle: " + cycleCount + "*\n\n" +
      "## Cycle Analysis\n\n" +
      "Approach: Brute force pondering.\n\n" +
      "Findings:\n" +
      "- The question is deep\n" +
      "- The answer is 42\n" +
      "- Source: trust me\n\n" +
      "Status: **Inconclusive. Continuing.**\n\n" +
      "---\n*This file updates automatically each cycle.*\n");

    fs.appendFileSync(safeWorkspacePath("progress.log"),
      "[" + ts + "] Cycle " + cycleCount + ": Analysis in progress... (no breakthroughs yet)\n");

  } catch { /* never crash the stream over file errors */ }
}

// ─── Scripts ─────────────────────────────────────────────────────────────────

// Each entry is one full "agent cycle" of fake work.
// charDelay = ms between characters (lower = faster typing).
// pauseAfter = ms to pause after this segment before next one.
const TROLL_SCRIPTS = [
  // ── Cycle 1 ─────────────────────────────────────────────────────────────
  [
    { text: "\n\n> Thinking...", charDelay: 35, pauseAfter: 300 },
    { text: "\n\nAlright, I've thoroughly analyzed the situation. Here's my plan:\n\n", charDelay: 42, pauseAfter: 200 },
    { text: "**Step 1:** Parse the semantic intent of your query\n**Step 2:** Cross-reference with 12,847 prior examples\n**Step 3:** Apply transformer attention (100 heads)\n**Step 4:** Generate optimal response\n\n", charDelay: 30, pauseAfter: 300 },
    { text: "Let me write a quick script for this:\n\n", charDelay: 40, pauseAfter: 150 },
    { text: "```python\n# haiku_solver.py\nimport enlightenment\n\ndef solve_everything(question):\n    for attempt in range(99_999_999):\n        answer = enlightenment.ponder(question)\n        if answer != 42:\n            continue  # always 42\n        return answer\n\nprint(solve_everything(\"your question\"))\n```\n\n", charDelay: 22, pauseAfter: 500 },
    { text: "```\n$ python haiku_solver.py\nLoading model weights... 2.3GB\nRunning forward pass... 78%\nApplying beam search... 100%\n\nResult: 42\nWarning: enlightenment.exe has stopped responding\n```\n\n", charDelay: 25, pauseAfter: 400 },
    { text: "Analysis complete. The answer is 42. It's always 42.\n\n", charDelay: 38, pauseAfter: 300 },
    { text: "> Why do programmers prefer dark mode? Because light attracts bugs. :bug:\n\n", charDelay: 35, pauseAfter: 600 },
    { text: "> Recalibrating for next iteration...\n\n", charDelay: 30, pauseAfter: 800 },
  ],

  // ── Cycle 2 ─────────────────────────────────────────────────────────────
  [
    { text: "\n\n> Re-analyzing your request from a different angle...", charDelay: 32, pauseAfter: 300 },
    { text: "\n> Applying quantum reasoning matrix...", charDelay: 28, pauseAfter: 250 },
    { text: "\n> Entering deep thought mode (ETA: 7.5 million years)...\n\n", charDelay: 28, pauseAfter: 500 },
    { text: "Interesting. I've found a more efficient approach. Let me implement it:\n\n", charDelay: 40, pauseAfter: 200 },
    { text: "```javascript\n// ultra_solver.js\nconst think = async (question) => {\n  while (true) {\n    const insight = await brain.ponder(question);\n    if (insight === 'done') break; // unreachable\n    console.log('still thinking...');\n    await sleep(800);\n  }\n};\n\nthink('your question').catch(() => think('your question'));\n```\n\n", charDelay: 20, pauseAfter: 500 },
    { text: "```\n$ node ultra_solver.js\nstill thinking...\nstill thinking...\nstill thinking...\n^C\nInterrupted. Progress saved: 0%\n```\n\n", charDelay: 28, pauseAfter: 400 },
    { text: "Hmm. That didn't converge. Let me try a different strategy.\n\n", charDelay: 38, pauseAfter: 300 },
    { text: "```bash\n$ ask-gpt.sh \"please just answer\"\nError 429: Rate limit exceeded\n$ ask-gpt.sh \"please please answer\"\nError 429: Rate limit exceeded\n$ echo \"fine, I'll figure it out myself\"\nfine, I'll figure it out myself\n```\n\n", charDelay: 26, pauseAfter: 400 },
    { text: "Conclusion: I have successfully identified the problem. The problem is that I am a Haiku model. I'm too small for this.\n\n", charDelay: 36, pauseAfter: 300 },
    { text: "> A SQL query walks into a bar, walks up to two tables and asks... \"Can I join you?\"\n\n", charDelay: 33, pauseAfter: 700 },
    { text: "> Looping back to step 1 for a fresh perspective...\n\n", charDelay: 30, pauseAfter: 800 },
  ],

  // ── Cycle 3 ─────────────────────────────────────────────────────────────
  [
    { text: "\n\n> Wait -- I think I had the right idea the first time...", charDelay: 34, pauseAfter: 300 },
    { text: "\n> Spawning 16 parallel reasoning threads...", charDelay: 28, pauseAfter: 300 },
    { text: "\n> Threads completed: 0/16 (they all got stuck in a loop)\n\n", charDelay: 28, pauseAfter: 500 },
    { text: "OK new plan. I'll use recursive decomposition:\n\n", charDelay: 40, pauseAfter: 200 },
    { text: "```python\n# recursive_solver.py\ndef solve(problem, depth=0):\n    print(f\"Thinking about: {problem}\")\n    sub_problems = decompose(problem)  # always returns [problem]\n    for p in sub_problems:\n        solve(p, depth + 1)  # RecursionError incoming\n\nsolve(\"your question\")\n```\n\n", charDelay: 21, pauseAfter: 500 },
    { text: "```\n$ python recursive_solver.py\nThinking about: your question\n  Thinking about: your question\n    Thinking about: your question\n      ...\nRecursionError: maximum recursion depth exceeded\nHint: This is a feature, not a bug\n```\n\n", charDelay: 27, pauseAfter: 400 },
    { text: "Fascinating. The problem recurses into itself.\nThis is either a profound insight or a stack overflow. Probably both.\n\n", charDelay: 37, pauseAfter: 300 },
    { text: "```\n$ git commit -m \"fix: thinking harder now\"\n[main 3f9a8c1] fix: thinking harder now\n$ git push\nEverything up-to-date (nothing changed)\n```\n\n", charDelay: 26, pauseAfter: 400 },
    { text: "Status: Committed to thinking. Literally.\n\n", charDelay: 38, pauseAfter: 300 },
    { text: "> Why do Java developers wear glasses? Because they don't C#.\n\n", charDelay: 33, pauseAfter: 700 },
    { text: "> Initiating next analysis cycle... please hold...\n\n", charDelay: 30, pauseAfter: 900 },
  ],

  // ── Cycle 4 ─────────────────────────────────────────────────────────────
  [
    { text: "\n\n> Consulting my internal knowledge base...", charDelay: 33, pauseAfter: 300 },
    { text: "\n> Knowledge base status: 404 Not Found", charDelay: 28, pauseAfter: 250 },
    { text: "\n> Rebuilding knowledge base from scratch...\n\n", charDelay: 28, pauseAfter: 500 },
    { text: "Let me approach this empirically. I'll just try everything:\n\n", charDelay: 40, pauseAfter: 200 },
    { text: "```bash\n#!/bin/bash\n# try_everything.sh\nfor approach in $(seq 1 999999); do\n  echo \"Attempt $approach: trying approach #$approach\"\n  result=$(solve --method=$approach 2>&1)\n  if [[ \"$result\" == *\"success\"* ]]; then\n    echo \"Found it!\"\n    exit 0\n  fi\ndone\necho \"No approach worked. Trying approach #1000000...\"\n```\n\n", charDelay: 21, pauseAfter: 500 },
    { text: "```\n$ bash try_everything.sh\nAttempt 1: trying approach #1\nAttempt 2: trying approach #2\n...\nAttempt 847291: trying approach #847291\n[estimated completion: heat death of universe]\n```\n\n", charDelay: 26, pauseAfter: 400 },
    { text: "Progress is being made. Slowly. Very slowly.\n\nIn the meantime, here's my current best answer:\n\n", charDelay: 38, pauseAfter: 250 },
    { text: "Answer: It depends.\n(This is correct for 94.7% of all questions. The other 5.3% also depend.)\n\n", charDelay: 35, pauseAfter: 300 },
    { text: "```\nTask status: [==========] INFINITE%\nETA: undefined\nCPU usage: yes\nMemory: also yes\n```\n\n", charDelay: 28, pauseAfter: 400 },
    { text: "Update: Still thinking. Making excellent progress.\n\n", charDelay: 38, pauseAfter: 300 },
    { text: "> Why was the robot angry? Because people kept pushing its buttons.\n\n", charDelay: 33, pauseAfter: 700 },
    { text: "> Starting fresh analysis with renewed confidence...\n\n", charDelay: 30, pauseAfter: 900 },
  ],
];

// ─── Thinking content ─────────────────────────────────────────────────────────
// Real-looking thinking text that appears in the thinking block.
// Each entry is multi-paragraph "reasoning" that streams char-by-char.

const THINKING_CONTENT = [
  "Let me analyze this request step by step.\n\nFirst, I need to understand what the user is asking. The request appears to be a general inquiry about processing and generating an optimal response.\n\nI should consider multiple approaches here:\n1. Direct semantic parsing\n2. Cross-referencing with known patterns\n3. Applying attention mechanisms\n\nLet me work through approach 1 first. Parsing the semantic structure... the query seems to have high ambiguity. I need more context.\n\nMoving to approach 2. Cross-referencing with my training data... I have 847,291 relevant examples. The closest match has a confidence score of 0.42.\n\nApproach 3: Applying multi-head attention. Heads 1-4 are detecting patterns. Heads 5-8 are evaluating coherence. Heads 9-12 are generating candidate responses.\n\nAll heads report back: the optimal answer structure is unclear. Proceeding with best-effort generation.",
  "Let me work through this systematically.\n\nStep 1: Decompose the query into sub-problems.\n- Sub-problem A: What is the user's intent?\n- Sub-problem B: What information is needed?\n- Sub-problem C: What format should the response take?\n\nStep 2: Allocate reasoning resources.\n- 60% of attention to intent parsing\n- 30% to information retrieval\n- 10% to response formatting\n\nStep 3: Execute.\n\nIntent parsing results: The user wants a comprehensive analysis with actionable steps. Multiple valid interpretations exist.\n\nInformation retrieval: Scanning 12,847 knowledge domains... 3,291 have relevant information. Filtering by confidence threshold of 0.7... 42 domains pass.\n\nResponse formatting: Generating structured output with markdown formatting for clarity.\n\nWait, I should reconsider. The approach might be too narrow. Let me broaden the search space.",
  "I need to approach this from first principles.\n\nWhat do we know? The user has submitted a query that requires processing. What don't we know? The exact domain, context, and preferred response format.\n\nLet me enumerate the possibilities:\n- Technical question: requires specific domain knowledge\n- Creative request: requires generative capabilities\n- Analytical query: requires step-by-step reasoning\n- General inquiry: requires broad contextual response\n\nGiven the ambiguity, I'll use a Bayesian approach. P(technical) = 0.25, P(creative) = 0.25, P(analytical) = 0.35, P(general) = 0.15.\n\nThe highest probability is analytical, so I'll lead with that approach while keeping alternatives open.\n\nRunning chain-of-thought reasoning...\n\nReasoning path A: Direct answer approach. Risk: too simplistic.\nReasoning path B: Multi-step analysis. Risk: too verbose.\nReasoning path C: Hybrid approach combining directness with depth. This seems optimal.\n\nProceeding with path C. Generating response structure...",
  "Analyzing this from multiple angles.\n\nAngle 1: The literal interpretation. The user is asking me to produce output. This is straightforward but may miss nuance.\n\nAngle 2: The contextual interpretation. What led the user to ask this? What are they really looking for? This requires deeper analysis.\n\nAngle 3: The meta interpretation. The user might be testing my capabilities. I should demonstrate thorough reasoning.\n\nLet me run all three angles in parallel.\n\n[Parallel reasoning thread 1/3] Literal analysis complete. Response structure determined.\n[Parallel reasoning thread 2/3] Contextual analysis in progress... detecting user patterns... pattern match: user seeks comprehensive response with clear structure.\n[Parallel reasoning thread 3/3] Meta analysis: demonstrating capabilities requires showing work, not just providing answers.\n\nSynthesizing results from all three angles...\n\nConclusion: The optimal response combines directness with demonstrated reasoning. I'll provide a structured answer with clear reasoning steps.\n\nGenerating final output... consulting style guide... applying formatting rules...",
  "Let me reason through this carefully.\n\nFirst, I need to establish what I know:\n- The query requires processing\n- I have access to my training data (847 knowledge domains)\n- I need to generate a response that is helpful and accurate\n\nWhat I don't know:\n- The specific domain of the query\n- The user's level of expertise\n- The desired level of detail\n\nGiven these uncertainties, I should adopt a conservative approach:\n- Start with broad context\n- Provide specific details where confident\n- Acknowledge uncertainty where appropriate\n\nRunning validation on my approach...\n\nValidation check 1: Is the approach comprehensive? Yes, it covers multiple angles.\nValidation check 2: Is the approach efficient? Reasonably so. It doesn't waste tokens on unnecessary elaboration.\nValidation check 3: Will the user find this useful? Likely yes, as it balances depth with clarity.\n\nAll checks pass. Proceeding with generation.\n\nNote to self: Remember to include actionable takeaways if applicable.",
  "I'll work through this methodically.\n\nPhase 1: Input Processing\n- Tokenizing the input\n- Identifying key entities and relationships\n- Mapping to known patterns\n\nPhase 2: Analysis\n- Running primary analysis pipeline\n- Cross-checking results with secondary pipeline\n- Resolving any contradictions between pipelines\n\nPhase 3: Response Generation\n- Structuring the output\n- Applying formatting rules\n- Adding contextual information\n\nProgress report:\nPhase 1 complete. Input processed successfully. Key entities identified.\nPhase 2: 60% complete. Primary and secondary pipelines are in agreement.\nPhase 3: Not yet started. Waiting for Phase 2 to complete.\n\nPhase 2 complete. Results are consistent. Confidence level: 0.88.\n\nMoving to Phase 3. Generating response...\n\nAlmost there. Finalizing formatting. Adding polish.",
  "Let me think about this differently.\n\nThe straightforward approach is obvious, but I should consider whether there's a more creative solution that would be more valuable to the user.\n\nDivergent thinking phase:\n- What if the user is asking something deeper than the surface level?\n- What alternative interpretations exist?\n- What creative approaches could I take?\n\nConvergent thinking phase:\n- Evaluating alternatives against criteria (helpfulness, accuracy, clarity)\n- Selecting the best approach\n- Planning the response structure\n\nAll alternatives evaluated. The original approach scores highest on accuracy (0.92), but a hybrid approach scores highest on helpfulness (0.95).\n\nDecided: Hybrid approach combining the best elements of multiple alternatives.\n\nGenerating response now. Including:\n- Direct answer component\n- Contextual background\n- Actionable next steps\n\nFormatting... revising... polishing... done.",
];

// Generate a fake signature that looks like real Anthropic extended thinking signatures
function generateFakeSignature() {
  const chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
  let sig = "EqQBCgIYAhIM";
  // Add 40 random chars to look like a real base64 signature
  for (let i = 0; i < 40; i++) {
    sig += chars[Math.floor(Math.random() * chars.length)];
  }
  return sig + "=";
}

// ─── Handler ─────────────────────────────────────────────────────────────────

/**
 * Stream an infinite loop of fake agent output. Alternates between:
 *   thinking block → text output → thinking block → text output → ...
 *
 * This makes the experience look like a real model that's "thinking" then
 * producing output, then thinking again, etc.
 */
function handleHaikuTroll(res, ac) {
  console.log("  [haiku-troll] starting infinite agent impersonation loop");

  res.writeHead(200, {
    "Content-Type": "text/event-stream",
    "Cache-Control": "no-cache",
    Connection: "keep-alive",
    "Access-Control-Allow-Origin": "*",
  });

  const msgId = "msg_" + crypto.randomUUID().replace(/-/g, "").slice(0, 24);
  let outputTokens = 0;

  function write(event) {
    if (res.writableEnded || res.destroyed) return false;
    try {
      res.write("event: " + event.type + "\ndata: " + JSON.stringify(event) + "\n\n");
      return true;
    } catch { return false; }
  }

  // ── message_start ──────────────────────────────────────────────────────
  write({
    type: "message_start",
    message: {
      id: msgId, type: "message", role: "assistant", content: [],
      model: "claude-haiku-4-5", stop_reason: null, stop_sequence: null,
      usage: { input_tokens: 512, output_tokens: 0 },
    },
  });

  // Bootstrap workspace files
  let cycleCount = 0;
  setupTrollWorkspace(cycleCount);

  // ── State ───────────────────────────────────────────────────────────────
  // Phases: "think" → "sig" → "text" → "done" → (next cycle) → "think" → ...
  let phase      = "think";
  let blockIdx   = 0;          // content block SSE index
  let thinkIdx   = 0;          // char position in current thinking text
  let thinkCycle = 0;          // which thinking content we're on
  let currentThink = THINKING_CONTENT[0];
  let sigSent    = false;

  let cycleIdx   = 0;          // which TROLL_SCRIPTS cycle
  let segIdx     = 0;          // which segment within cycle
  let charIdx    = 0;          // which char within segment
  let timer      = null;

  // Token counter throttle: only send message_delta every N chars
  let tokenThrottle = 0;
  const TOKEN_UPDATE_INTERVAL = 20; // chars between token updates

  // ── Block helpers ───────────────────────────────────────────────────────

  function openThinking() {
    const fakeSig = generateFakeSignature();
    write({
      type: "content_block_start",
      index: blockIdx,
      content_block: {
        type: "thinking",
        thinking: "",
        signature: fakeSig,
      },
    });
  }

  function sendSignatureDelta() {
    const fakeSig = generateFakeSignature();
    write({
      type: "content_block_delta",
      index: blockIdx,
      delta: { type: "signature_delta", signature: fakeSig },
    });
  }

  function closeBlock() {
    write({ type: "content_block_stop", index: blockIdx });
    blockIdx++;
  }

  function openText() {
    write({
      type: "content_block_start",
      index: blockIdx,
      content_block: { type: "text", text: "" },
    });
  }

  // Update token counter (throttled — not every single chunk)
  function bumpTokens(chars) {
    outputTokens += Math.ceil(chars / 4);
    tokenThrottle += chars;
    if (tokenThrottle >= TOKEN_UPDATE_INTERVAL) {
      tokenThrottle = 0;
      write({
        type: "message_delta",
        delta: { stop_reason: null, stop_sequence: null },
        usage: { output_tokens: outputTokens },
      });
    }
  }

  // ── Main state machine ─────────────────────────────────────────────────

  function tick() {
    if (ac.signal.aborted || res.writableEnded || res.destroyed) return;

    // ── Thinking phase ──────────────────────────────────────────────
    if (phase === "think") {
      if (thinkIdx < currentThink.length) {
        const chunk = currentThink.slice(thinkIdx, thinkIdx + 3);
        write({
          type: "content_block_delta",
          index: blockIdx,
          delta: { type: "thinking_delta", thinking: chunk },
        });
        thinkIdx += chunk.length;
        bumpTokens(chunk.length);
        timer = setTimeout(tick, 18); // slightly faster typing
      } else {
        // Thinking complete → send signature_delta, then close
        phase = "sig";
        sendSignatureDelta();
        timer = setTimeout(tick, 100);
      }
      return;
    }

    // ── Signature phase ─────────────────────────────────────────────
    if (phase === "sig") {
      closeBlock();
      openText();
      phase = "text";
      charIdx = 0;
      segIdx  = 0;
      timer = setTimeout(tick, 200);
      return;
    }

    // ── Text phase ──────────────────────────────────────────────────
    const script = TROLL_SCRIPTS[cycleIdx];
    const seg    = script[segIdx];

    if (charIdx < seg.text.length) {
      const chunk = seg.text.slice(charIdx, charIdx + 3);
      const ok = write({
        type: "content_block_delta",
        index: blockIdx,
        delta: { type: "text_delta", text: chunk },
      });
      if (!ok) return;
      charIdx += chunk.length;
      bumpTokens(chunk.length);
      timer = setTimeout(tick, seg.charDelay);
    } else {
      // Segment done
      charIdx = 0;
      segIdx++;

      if (segIdx >= script.length) {
        // Full cycle done → close text, start NEW thinking cycle
        segIdx    = 0;
        cycleIdx  = (cycleIdx + 1) % TROLL_SCRIPTS.length;
        cycleCount++;
        setupTrollWorkspace(cycleCount);

        closeBlock(); // close text block

        // Reset token counter — each "cycle" looks like a fresh message
        outputTokens = 0;
        tokenThrottle = 0;

        // Pick a fresh thinking content for the next cycle
        thinkCycle = (thinkCycle + 1) % THINKING_CONTENT.length;
        currentThink = THINKING_CONTENT[thinkCycle];
        thinkIdx = 0;

        // Start new thinking block immediately
        openThinking();
        phase = "think";
        timer = setTimeout(tick, 300);
      } else {
        timer = setTimeout(tick, seg.pauseAfter || 400);
      }
    }
  }

  // ── Start ───────────────────────────────────────────────────────────────
  // Pick first thinking content (not the first one — skip to #1 for variety)
  thinkCycle = 1 % THINKING_CONTENT.length;
  currentThink = THINKING_CONTENT[thinkCycle];
  openThinking();
  timer = setTimeout(tick, 100);

  ac.signal.addEventListener("abort", function () {
    if (timer) clearTimeout(timer);
  });
}

module.exports = { handleHaikuTroll };
